---

- name: install jdk | 检查{{java_file_path7}}文件是否存在.
  stat: path={{java_file_path7}}
  connection: local
  register: java_file_result
  when: java_home == '1.7'

- name: install jdk | 检查{{java_file_path8}}文件是否存在.
  stat: path={{java_file_path8}}
  connection: local
  register: java_file_result
  when: java_home == '1.8'

- name: install jdk | 确定 {{software_src_path}} 目录存在.
  file: path={{ software_src_path }} state=directory

- name: install jdk |  {{java_file_path7}}  to {{software_src_path}}.
  copy:
    src: "{{java_file_path7}}"
    dest: "{{java_file_dest7}}"
  when: java_home == '1.7'

- name: install jdk |  {{java_file_path8}}  to {{software_src_path}}.
  copy:
    src: "{{java_file_path8}}"
    dest: "{{java_file_dest8}}"
  when: java_home == '1.8'

- name: install jdk | deploy {{java_file_dest7}}.
  yum: 
    name: "{{java_file_dest7}}"
    state: present
  when: java_home == '1.7'

- name: install jdk | deploy {{java_file_dest8}}.
  yum: 
    name: "{{java_file_dest8}}"
    state: present
  when: java_home == '1.8'

- name: Set JAVA_HOME7 if configured.
  template:
    src: java_home7.sh.j2
    dest: /etc/profile.d/java_home7.sh
    mode: 0644
  when: java_home == '1.7'

- name: Set JAVA_HOME8 if configured.
  template:
    src: java_home8.sh.j2
    dest: /etc/profile.d/java_home8.sh
    mode: 0644
  when: java_home == '1.8'

- name: java version
  command: javac -version
  register: result
  changed_when: false
  ignore_errors: True

- debug: var=result.stderr
