version: '2'
services:
    gitlab:
      image: 'twang2218/gitlab-ce-zh:10.8.7'
      restart: unless-stopped
      hostname: '10.26.10.76'
      environment:
        TZ: 'Asia/Shanghai'
        GITLAB_OMNIBUS_CONFIG: |
          external_url 'http://10.26.10.76'
          gitlab_rails['gitlab_shell_ssh_port'] = 2212
          gitlab_rails['time_zone'] = 'Asia/Shanghai'
          gitlab_rails['smtp_enable'] = true
          gitlab_rails['smtp_address'] = "smtp.qq.com"
          gitlab_rails['smtp_port'] = 465
          gitlab_rails['smtp_user_name'] = "417787129@qq.com"
          gitlab_rails['smtp_password'] = "ngjarjjoniwhcbcd"
          gitlab_rails['smtp_authentication'] = "login"
          gitlab_rails['smtp_enable_starttls_auto'] = true
          gitlab_rails['smtp_tls'] = true
          gitlab_rails['gitlab_email_from'] = '417787129@qq.com'
      ports:
        - '80:80'
        - '443:443'
        - '2212:22'
      volumes:
        - /data/gitlab/config:/etc/gitlab
        - /data/gitlab/data:/var/opt/gitlab
        - /data/gitlab/logs:/var/log/gitlab
