- name: 将 {{ app_user }} 加入 wheel 组
  user:
    state: present
    name: '{{ app_user }}'
    append: yes
    groups: wheel

- lineinfile:
    state: present
    insertafter: '^[ \t]*%wheel[ \t]+ALL[ \t]+=[ \t]+\(ALL\)[ \t]+NOPASSWD:[ \t]+ALL[ \t]+$'
    line: '%wheel  ALL=(ALL)       NOPASSWD: ALL'
    path: /etc/sudoers
    validate: /usr/sbin/visudo -cf %s
