---
- name: sync code
  synchronize:
    src: /data/code
    dest: /var/www/
    rsync_opts:
      - "--no-motd"
      - "--exclude=.git"
- name: file cofig set
  file:
    path: /var/www
    owner: www
    group: www
    mode: 0644